### ISSUE TITLE
Adding a fire option

### ISSUE THREAD

**Issue by MisterWapak** [PotatoCraft-Studio/CoreProtectTNT#13]
Hello, the plugin works perfectly !
I just want to suggest that you also add a fire log option. We still have today the classic "fire placed by fire" and it will be really great if we can see the name of the guy who started it.
Thank you for this great plugin :)

**Comment by Iaiao** [comment]
Hello and thanks for your feedback! The explosion source can be tracked even if the player makes a chain of ignitable blocks and burns them, and now you can also track individual blocks.
