### ISSUE TITLE
Tnt duper console spam

### ISSUE THREAD

**Issue by emielderckx** [PotatoCraft-Studio/CoreProtectTNT#17]
I know this plugin isn't in that active development anymore but I would love for this to be fixed <3

What is happening is that when tnt dupers are on the console get spammed a lot
https://mcpaste.io/0c5a82ab8d0f1252

**Comment by emielderckx** [comment]
You are a fucking hero!

**Comment by kyrtion** [comment]
> You are a fucking hero!

Are you not sended latest.log
